export default {
    awesomeMovie: "Lego Movie",
    awesomeCast: {
      Emmet: "Chris Pratt",
      Wyldstyle: "Elizabeth Banks",
      Batman: "Will Arnett",
      "President Business" : "Will Ferrell",
      Unikitty: "Alison Brie",
      Metalbeard: "Nick Offerman",
      Benny: "Charlie Day",
      Vitruvius: "Morgan Freeman",
      BadCop: "Liam Neeson",
    },
    awesomeThings: [
      "a nobel prize",
      "a piece of string",
      "dogs with fleas",
      "allergies",
      "a book of Greek antiquities",
      "brand new pants",
      "a very old vest",
      "trees",
      "frogs",
      "clogs",
      "rocks",
      "clocks",
      "socks",
      "figs",
      "jigs",
      "twigs",
    ],
  }